version: "3.9"

services:
  servidor-dados:
    build: .
    ports:
      - "5000:5000"
    networks:
      - servidores
    volumes:
      - ${PWD}/logs-servidor-dados:/app/logs
networks:
  servidores:
    name: servidores
    driver: bridge
